### ISSUE TITLE
What is the benefit of this library versus using csv files with Test.loadData(static_resource) method?

### ISSUE THREAD

**Issue by pgonzaleznetwork** [RetekBacsi/TestDataLoader#1]

**Comment by RetekBacsi** [comment]
There are a few in my opinion:
1. Organize test data by the function, not by data types. You can have a single static resouce per test class where you set up a complex scenario with different object types. I find it easier to work with a single file.
2. Refer profiles/roles/recordtypes etc without hardcoding ids (which can break between sandboxes)
3. Control over Date values. Let's say you have a requirement to do something with records where a date custom field's value in the next 7 days. Here you can set it to "TODAY + 3 DAYS", while with the standard loader the hard-coded values will expire and your tests will fail after a time.
4. Circular dependencies. Let's say you have an Account, a list of Contacts, and the Account has a "Main Contact" lookup. With the standard loader this is not possible.
5. The tool will figure out the dependency order*. You can define your data in any order rather than keeping in mind what needs to be loaded first. This results in more readable test data in my experience. (for circular references it requires hints)
6. No need to keep the same type of objects together. You can define the test data in an order to define your scenario. The library will group the objects and do only one insert per object type.
7. (Personal taste: I find XML files more readable, also I don't have to specify the same set of data for each record. It's possible to only concentrate on the important fields for the scenario)

**Comment by pgonzaleznetwork** [comment]
Hi @RetekBacsi ,

Thank you for this info! I'd recommend copy/pasting this to the readme file under a section titled just like this question, as others may have the exact same question.

I'm going to log a new issue as I'm having some issues with date/time fields.
